# /etc/apache2/conf-available/allsee.conf
# Apache 2.4 Configuration for AllSee AllStarLink Web Controller

Alias /allsee /var/www/html/allsee

<Directory /var/www/html/allsee>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted

    <IfModule mod_php7.c>
        php_flag display_errors Off
        php_value max_execution_time 30
    </IfModule>
    <IfModule mod_php.c>
        php_flag display_errors Off
        php_value max_execution_time 30
    </IfModule>
</Directory>
